const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const cpuinfoSchema = new Schema({
    imgurl:{
        type:String
    },
    name:{
        type:String
    },
    MPN:{
        type:String
    },
    Manufacturer:{
        type:String
    },
    ManufacturerURL:{
        type:String
    },
    Part:{
        type:String
    },
    CoreCount:{
        type:String
    },
    CoreClock:{
        type:String
    },
    BoostClock:{
        type:String
    },
    TDP:{
        type:String
    },
    Series:{
        type:String
    },
    Microarchitecture:{
        type:String
    },
    CoreFamily:{
        type:String
    },
    Socket:{
        type:String
    },
    IntegratedGraphics:{
        type:String
    },
    MaximumSupportedMemory:{
        type:String
    },
    ECCSupport:{
        type:String
    },
    IncludesCooler:{
        type:String
    },
    Packaging:{
        type:String
    },
    L1Cache:{
        type:String
    },
    L2Cache:{
        type:String
    },
    L3Cache:{
        type:String
    },
    Lithography:{
        type:String
    },
    IncludesCPUCooler:{
        type:String
    },
    SimultaneousMultithreading:{
        type:String
    }
})

module.exports = mongoose.model('cpuinfo', cpuinfoSchema)